server:
  port: 2000
sys:
  auth:
    tokenHeaderName: auth-token
    authTokenRedisPrefix: auth-token

spring:
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/bms?characterEncoding=utf-8
      username: root
      password: 123456
      configuration:
        maximum-pool-size: 20
    second:
      url: jdbc:mysql://localhost:3306/bms?characterEncoding=utf-8
      username: root
      password: 123456
      configuration:
        maximum-pool-size: 20
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
