#多数据源配置示例
spring:
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/first
      username: dbuser
      password: sd
      configuration:
        maximum-pool-size: 20
    second:
      url: jdbc:mysql://localhost:3306/second
      username: root
      password: 143234
      configuration:
        maximum-pool-size: 20
